In [1]:
!pip3 install torch torchvision

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 135.3 MB 179 kB/s  eta 0:00:01
     |████████████████████████████████| 1.4 MB 19.8 MB/s eta 0:00:01
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -m pip install --upgrade pip' command.


In [1]:
import torch

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
torch.__version__

'1.13.1'

## Create Tensor

In [11]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [14]:
#attributes

# number of dimensions
scalar.ndim

0

In [15]:
#return as integer
scalar.item()

7

### Vector

In [16]:
vector = torch.tensor([7,3])
vector

tensor([7, 3])

In [19]:
#vector dimensions
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


### MATRIX

In [27]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [28]:
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [34]:
#average of first list in matrix
sum(MATRIX[0][:]).item()

15

In [43]:
TENSOR = torch.tensor([[[1,1,1],
                       [2,2,2],
                       [3,3,3]]])
TENSOR

tensor([[[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]]])

In [44]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


In [40]:
#TAKES AN INDEX TO VIEW THE WHOLE TENSOR THATS WHY SIZE STARTS WITH 1^^^
# ' 1 - TENSOR'
TENSOR[0]

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [45]:
TENSOR = torch.tensor([[[[1,1,1],
                       [2,2,2],
                       [3,3,3]]]])
TENSOR

tensor([[[[1, 1, 1],
          [2, 2, 2],
          [3, 3, 3]]]])

In [50]:
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0][0])
print(TENSOR[0][0][0])

4
torch.Size([1, 1, 3, 3])
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])
tensor([1, 1, 1])


## Random Tensors
- look at random numbers, update data (random numbers), neural networks learn from random numbers

In [54]:
#Create a random tensor with size/shape of (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7112, 0.1457, 0.2331, 0.3806],
        [0.3056, 0.2860, 0.6279, 0.0920],
        [0.5211, 0.6722, 0.8943, 0.9543]])

In [55]:
random_tensor.shape

torch.Size([3, 4])

In [56]:
#count beginning and end square brackets
random_tensor.ndim

2

In [70]:
#10 tensors that are 10 in length and size
random_tensor = torch.rand(10, 10, 10)
#call the last tensor

In [72]:
random_tensor[-1]

tensor([[0.6177, 0.9149, 0.4811, 0.5153, 0.8384, 0.1183, 0.2541, 0.1750, 0.3442,
         0.1353],
        [0.2701, 0.2587, 0.6503, 0.0344, 0.9423, 0.6831, 0.9914, 0.0150, 0.5842,
         0.9072],
        [0.9723, 0.7309, 0.0230, 0.7874, 0.8400, 0.0217, 0.2302, 0.6795, 0.6009,
         0.0731],
        [0.3903, 0.1355, 0.7776, 0.6898, 0.6457, 0.7763, 0.8934, 0.7119, 0.5815,
         0.0295],
        [0.2215, 0.8186, 0.0209, 0.1406, 0.3350, 0.1690, 0.9836, 0.1585, 0.3734,
         0.6816],
        [0.5228, 0.9730, 0.9789, 0.2570, 0.2802, 0.4582, 0.2536, 0.4940, 0.9507,
         0.8210],
        [0.1844, 0.6656, 0.7529, 0.9746, 0.7919, 0.0402, 0.8280, 0.4841, 0.1548,
         0.7597],
        [0.4991, 0.3059, 0.6578, 0.1999, 0.2603, 0.9349, 0.7808, 0.0583, 0.7542,
         0.1923],
        [0.0178, 0.8046, 0.3301, 0.5390, 0.0951, 0.6028, 0.5479, 0.4603, 0.0625,
         0.6405],
        [0.5211, 0.6198, 0.5744, 0.7197, 0.8619, 0.2897, 0.5301, 0.1403, 0.6710,
         0.6084]])

## BASIC MATRIX ALGEBRA

In [74]:
random_tensor = torch.rand(3,4)
#TENSOR MATRIX WITH ALL ZEROS  -------- same dimension
zero_tensor = torch.zeros(size=(3,4))

In [75]:
random_tensor + zero_tensor

tensor([[0.7941, 0.8503, 0.8182, 0.7657],
        [0.8859, 0.5206, 0.4524, 0.3659],
        [0.6105, 0.3881, 0.7630, 0.3128]])

In [79]:
ones_tensor = torch.ones(size=(3,4))
print(random_tensor + ones_tensor)

#data TYPE
ones_tensor.dtype

tensor([[1.7941, 1.8503, 1.8182, 1.7657],
        [1.8859, 1.5206, 1.4524, 1.3659],
        [1.6105, 1.3881, 1.7630, 1.3128]])


torch.float32

## Create a range

In [84]:
#range of numbers 0-9
one_nine = torch.arange(0,10)
one_nine

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
#range of numbers 1-11 step by 2
one_eleven = torch.arange(1,11,2)
one_eleven

tensor([1, 3, 5, 7, 9])

In [89]:
#CREATE ALIKE TENSOR
print(one_nine.ndim)
print(one_nine.shape)

1
torch.Size([10])


In [94]:
zeros = torch.zeros_like(input=one_nine)
zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [95]:
ones = torch.ones_like(input=one_nine)
ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## CONVERT TENSOR DATA TYPE

In [101]:
MATRIX = torch.tensor([[0,1,1],
                      [1,2,2]],
                     dtype=None,
                     device=None)
MATRIX

tensor([[0, 1, 1],
        [1, 2, 2]])

In [103]:
MATRIX.dtype

torch.int64

In [105]:
#CHANGE TO FLOAT 16 bit
float_16_tensor = MATRIX.type(torch.float16)
float_16_tensor

tensor([[0., 1., 1.],
        [1., 2., 2.]], dtype=torch.float16)

In [106]:
float_16_tensor + MATRIX

tensor([[0., 2., 2.],
        [2., 4., 4.]], dtype=torch.float16)

## Information from Tensors

In [108]:
#create tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4035, 0.5063, 0.8787, 0.2229],
        [0.2533, 0.3668, 0.5613, 0.8926],
        [0.4276, 0.7654, 0.8034, 0.6426]])

In [110]:
print(some_tensor.ndim)
print(some_tensor.shape)
#device tensor is on
some_tensor.device

2
torch.Size([3, 4])


device(type='cpu')

## Manipulating tensors

In [4]:
#addition of each element
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [8]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [5]:
#subtraction of each element
tensor-10

tensor([-9, -8, -7])

In [6]:
#Multiplication of each element
tensor*10

tensor([10, 20, 30])

In [7]:
torch.mul(tensor,10) 

tensor([10, 20, 30])

In [119]:
#division of each element
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [120]:
#view modulo/remainder
tensor%2

tensor([1, 0, 1])

In [122]:
#floor division
tensor//2

tensor([0, 1, 1])

## MATRIX MULTIPLICATION
- ELEMENT WISE
- DOT PRODUCT!!

### two main rools that matrix multiplication needs to satisfy:
    - 1.) inner dimensions must match
* `(3,2) @ (3,2)` wont work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

    - 2.) Resulting matrix has the shape of the outer dimensions
*`(2,3) @ (3,2)` --> `(2,2)`
*`(3,2) @ (2,3)` --> `(3,3)`

In [26]:
rand_tensor = torch.rand(3,2) #specify shape
rand_tensor

tensor([[0.4103, 0.2710],
        [0.9805, 0.2416],
        [0.9804, 0.1634]])

In [28]:
torch.matmul(rand_tensor,rand_tensor)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [29]:
#NOW THE INNER DIMENSIONS MATCH 😃
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.8970, 0.4232],
        [0.6163, 0.4646]])

In [38]:
#View in more detail ^
tensor1 = torch.rand(2,3)
print(tensor1)
print()
tensor2 = torch.rand(3,2)
print(tensor2)
print()

torch.matmul(tensor1,tensor2) #EACH NUMBER HAS A CORRESPONDENT TO MULTIPLY -- THEN VALS CAN ALL BE ADDED

tensor([[0.2251, 0.1491, 0.7873],
        [0.4574, 0.8640, 0.5780]])

tensor([[0.3596, 0.2758],
        [0.1028, 0.4469],
        [0.0493, 0.3473]])



tensor([[0.1351, 0.4022],
        [0.2818, 0.7130]])

In [14]:
print(tensor)
tensor*tensor

tensor([1, 2, 3])


tensor([1, 4, 9])

In [23]:
tensor.shape

torch.Size([3])

In [15]:
#Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [21]:
#Matrix multiplication
tensor @ tensor

tensor(14)

In [20]:
#by hand
1*1 + 2*2 + 3*3

14

## Shape errors ^

In [57]:
tensor_a = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_b = torch.tensor([[7,10],
                        [7,11],
                        [9,12]])

#3X2 AND 3X2 ---> INNER DIMENSIONS DONT MATCH -- CANT MULTIPLY
tensor_a.shape, tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [60]:
1*7+1*7+1*9

23

#### to fix shape error --> use **transpose**
**transpose** changes dimensions of one tensor

In [58]:
tensor_b = tensor_b.T # 3x2 into 2x3
tensor_b

tensor([[ 7,  7,  9],
        [10, 11, 12]])

In [62]:
torch.matmul(tensor_a, tensor_b)

tensor([[ 27,  29,  33],
        [ 61,  65,  75],
        [ 95, 101, 117]])

In [63]:
tensor_a.shape, tensor_b.shape #INNER DIMENSIONS ARE SAME

(torch.Size([3, 2]), torch.Size([2, 3]))

## MANIPULATION OF TWO TENSORS (more below)

In [124]:
tensor = torch.tensor([[1,2,3],
                       [10,20,30]])

print(tensor.ndim)
print(tensor.shape)

2
torch.Size([2, 3])


In [128]:
other_tensor = torch.rand(2,3)
other_tensor

tensor([[0.6856, 0.5066, 0.8068],
        [0.4065, 0.1969, 0.7626]])

In [129]:
tensor + other_tensor

tensor([[ 1.6856,  2.5066,  3.8068],
        [10.4065, 20.1969, 30.7626]])

# Tensor Aggregation
#### min,max,sum,etc.

In [65]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [70]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [71]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [73]:
#IN ORDER TO AVERAGE MUST BE IN FLOAT!!!
x.dtype

torch.int64

In [78]:
#average the float through converting datatype from int-->float
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [80]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
#elements count in tensors in tensors

## FINDING INDEX OF min/max^
- USE `arg`

In [82]:
x, x.argmin()

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), tensor(0))

In [85]:
x.argmax(), x[x.argmax()] #max value at index 9

(tensor(9), tensor(90))

## Reshaping, stacking, squeezing, and unsqueezing
* reshaping - reshapes tensor to specified shape
* view - view tensor and share memory as the original
* stacking - combine multiple tensors on top of each other (vstack) or side-side (hstack)
* squeeze - removes all `1` dimensions from tensor
* unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [87]:
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [89]:
#NEW SHAPE HAS TO BE COMPATIBLE WITH ORIGINAL ARRAY (FIT ALL NUMBERS)
x.reshape(1,9) #another dimension added (another square bracket at beggining+end)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [90]:
x.reshape(9,1) #all numbers accomadated 

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [102]:
#another example
x = torch.arange(1,12,2)
x, x.shape

(tensor([ 1,  3,  5,  7,  9, 11]), torch.Size([6]))

In [99]:
x.reshape(3,2)

tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]])

#### view

In [107]:
#VIEW
x = torch.arange(1,10) 
z = x.view(1,9)
x, x.shape, z, z.shape #dimension added but original kept in memory

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 torch.Size([9]),
 tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 torch.Size([1, 9]))

In [111]:
#changing z changes x
z[:,0] = 5 #changing first element in z to 5 changes it in x as well
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

#### stack

In [123]:
#Stack tensors
#stack dimension 0 (vertical stack)
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [131]:
#vertical stack
torch.vstack([x,x,x,x])

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [122]:
#stack dimension 1 (down middle)
torch.stack([x,x,x,x], dim=1)

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [130]:
#horizontal stack
torch.hstack([x,x,x,x])

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9, 5, 2, 3, 4, 5, 6, 7, 8, 9, 5, 2, 3, 4, 5, 6,
        7, 8, 9, 5, 2, 3, 4, 5, 6, 7, 8, 9])

#### Squeeze + Unsqueeze

In [150]:
#torch.squeeze() - removes all single dimensions from a target tensor
x = torch.zeros(2,1,2,1,2)
print(x.shape)
print(x)
x = x.squeeze()
print(x.shape)
x


torch.Size([2, 1, 2, 1, 2])
tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])
torch.Size([2, 2, 2])


tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [165]:
x = torch.arange(1,10).reshape(1,9)
print(x, x.shape)
x = x.squeeze()
x, x.shape

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 9])


(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [175]:
x = torch.arange(1,10).reshape(3,3,1)
print(x, x.shape)
x = x.squeeze(2)
x, x.shape

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]]) torch.Size([3, 3, 1])


(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))